
payment-api:
  title: Payment APIs
  description: APIs do Módulo Pagamento
  version: @project.version@
  endpointsPackage: br.com.will.poc.payment

server:
  port: 8082
  servlet:
    context-path: /payment-api

spring:
  application:
    name: PAYMENT API
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
    mongodb:
      host: localhost
      port: 27017
      database: iupp_mongo_db
      username: iupp_mongo
      password: iupp_mongo
  datasource:
    url: jdbc:postgresql://localhost:5432/iupp-order
    username: iupp-order
    password: iupp-order
    hikari:
      pool-name: iupp-payment-pool
      idle-timeout: 120000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 300000
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: true
    create-schemas: true
    schemas: iupp_payment
    check-location: false
  jpa:
    open-in-view: false
    database: postgresql
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.time_zone: UTC
      hibernate.enable_lazy_load_no_trans: true
      hibernate.default_schema: iupp_payment
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
    time-zone: America/Sao_Paulo

axon:
  axonserver:
    servers: localhost
